spring.application.name=ugflweb

server.port=9000
jhipster.clientApp.name=ugflweb
# Local MySQL config
app.datasource.mysql.username=root
app.datasource.mysql.password=admin
app.datasource.mysql.driver-class-name=com.mysql.cj.jdbc.Driver
app.datasource.mysql.url=jdbc:mysql://localhost:3306/unigold_app
#app.upload.path=C:\\Users\\Admin\\Downloads\\EmailExtractor
app.upload.path=/home/UnigoldUpload
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.override-with-generic-response=false
springdoc.override-with-problem-descriptor=false
springdoc.controller-advice.exclude=com.elexyt.ugflweb.error.ExceptionTranslator

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.http.multipart.enabled=true

# JWT
jwt.expirationDateInMs=700000000
jwt.refreshExpirationDateInMs=9000000
jwt.secret=tmshgjhkjlghjhkjklkkhgjmjhkjklkk

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=1
spring.flyway.locations=classpath:db/migration


#Mail configuration
spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.username=ommprakash.primgradus@gmail.com
spring.mail.password=bltrwgkjdkuflncx
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true